name: Test, Build & Deploy on Digital Ocean
on: [push, pull_request]
jobs:
  #test:

  #  name: Test
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: borales/actions-yarn@v2.3.0
  #      with:
  #        cmd: install # will run `yarn install` command
  #    - uses: borales/actions-yarn@v2.3.0
  #      with:
  #        cmd: test # will run `yarn test` command

  deploy:
    name: Build & Deploy on Digital Ocean
    #needs: test
    runs-on: ubuntu-latest
    # Only when pushing onto main (or merging PR)
    #if: github.event_name == 'push' && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.DO_HOST }}
          remote-user: ${{ secrets.DO_HOST }}
          ssh-private-key: ${{ secrets.DO_KEY }}
          local-path: "."
          remote-path: "/var/www/html"
    #  - uses: borales/actions-yarn@v2.3.0
    #    with:
    #      cmd: install # will run `yarn install` command
    #  - uses: borales/actions-yarn@v2.3.0
    #    with:
    #      cmd: build # will run `yarn test` command
    #  - name: deploy file to server
    #    uses: wlixcc/SFTP-Deploy-Action@v1.0
    #    with:
    #      username: '${{ secrets.DO_USER }}'
    #      server: '${{ secrets.DO_HOST }}'
    #      ssh_private_key: ${{ secrets.DO_KEY }}
    #      local_path: './build/*'
    #      remote_path: '/var/www/html'
    #      args: '-o ConnectTimeout=5'

