name: Test, Build & Deploy on Digital Ocean
on: [push, pull_request]
jobs:
  #test:

  #  name: Test
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: borales/actions-yarn@v2.3.0
  #      with:
  #        cmd: install # will run `yarn install` command
  #    - uses: borales/actions-yarn@v2.3.0
  #      with:
  #        cmd: test # will run `yarn test` command

  deploy:
    name: Build & Deploy on Digital Ocean
    #needs: test
    runs-on: ubuntu-latest
    # Only when pushing onto main (or merging PR)
    #if: github.event_name == 'push' && ${{ github.ref == 'refs/heads/main' }}
    steps:
    #  - uses: borales/actions-yarn@v2.3.0
    #    with:
    #      cmd: install # will run `yarn install` command
    #  - uses: borales/actions-yarn@v2.3.0
    #    with:
    #      cmd: build # will run `yarn test` command
      - uses: actions/checkout@v2
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          source: "."
          target: "/var/www/html"

